name: Docker Push

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Install Docker Composer
        run: sudo apt -y update && sudo apt install -y docker-compose

      - name: Docker Build
        run: docker-compose build

      - name: Docker Push
        run: docker push tmvdl/projects -a
