name: docker pull

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker pull
        run: docker pull tmvdl/projects -a
